/**
 * Stable, machine-readable error codes. Clients branch on these — never on
 * message text and never on HTTP status alone. Codes are append-only: renaming
 * one is a breaking API change.
 */
export enum ErrorCode {
  // Generic
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
  RESOURCE_LOCKED = 'RESOURCE_LOCKED',
  CONFLICT = 'CONFLICT',
  /** A request carried a Mongo operator ($-prefixed) key — likely injection. */
  SUSPECT_INPUT_REJECTED = 'SUSPECT_INPUT_REJECTED',

  // Auth — registration
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  PHONE_ALREADY_REGISTERED = 'PHONE_ALREADY_REGISTERED',
  IDENTIFIER_REQUIRED = 'IDENTIFIER_REQUIRED',
  WEAK_PASSWORD = 'WEAK_PASSWORD',

  // Auth — session
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  FORBIDDEN = 'FORBIDDEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  REFRESH_TOKEN_REUSED = 'REFRESH_TOKEN_REUSED',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',

  // Auth — account state
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',
  ACCOUNT_NOT_VERIFIED = 'ACCOUNT_NOT_VERIFIED',
  ALREADY_VERIFIED = 'ALREADY_VERIFIED',

  // Account lifecycle
  ACCOUNT_PENDING_DELETION = 'ACCOUNT_PENDING_DELETION',
  ACCOUNT_NOT_PENDING_DELETION = 'ACCOUNT_NOT_PENDING_DELETION',
  RESTORE_WINDOW_EXPIRED = 'RESTORE_WINDOW_EXPIRED',

  // Onboarding / taxonomy
  ONBOARDING_STEP_UNKNOWN = 'ONBOARDING_STEP_UNKNOWN',
  ONBOARDING_INCOMPLETE = 'ONBOARDING_INCOMPLETE',
  ONBOARDING_ALREADY_COMPLETE = 'ONBOARDING_ALREADY_COMPLETE',
  TAXONOMY_VALUE_INVALID = 'TAXONOMY_VALUE_INVALID',

  // Wishlists
  WISHLIST_NOT_FOUND = 'WISHLIST_NOT_FOUND',
  WISHLIST_ARCHIVED = 'WISHLIST_ARCHIVED',
  WISHLIST_ITEM_NOT_FOUND = 'WISHLIST_ITEM_NOT_FOUND',
  WISHLIST_ITEM_LOCKED = 'WISHLIST_ITEM_LOCKED',
  WISHLIST_LIMIT_REACHED = 'WISHLIST_LIMIT_REACHED',

  // Wishlist access
  PARTICIPANT_NOT_FOUND = 'PARTICIPANT_NOT_FOUND',
  PARTICIPANT_ALREADY_EXISTS = 'PARTICIPANT_ALREADY_EXISTS',
  CANNOT_INVITE_OWNER = 'CANNOT_INVITE_OWNER',
  SHARE_LINK_INVALID = 'SHARE_LINK_INVALID',
  SHARE_LINK_EXPIRED = 'SHARE_LINK_EXPIRED',
  SHARE_PASSCODE_REQUIRED = 'SHARE_PASSCODE_REQUIRED',
  SHARE_PASSCODE_INVALID = 'SHARE_PASSCODE_INVALID',

  // Gifting
  GIFT_NOT_FOUND = 'GIFT_NOT_FOUND',
  ITEM_NOT_AVAILABLE = 'ITEM_NOT_AVAILABLE',
  ITEM_ALREADY_CLAIMED = 'ITEM_ALREADY_CLAIMED',
  CANNOT_GIFT_OWN_ITEM = 'CANNOT_GIFT_OWN_ITEM',
  NOT_THE_GIFTER = 'NOT_THE_GIFTER',
  INVALID_GIFT_TRANSITION = 'INVALID_GIFT_TRANSITION',
  RESERVATION_EXPIRED = 'RESERVATION_EXPIRED',
  IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED',
  // ── Wishmates ──────────────────────────────────────────────────────────
  USERNAME_TAKEN = 'USERNAME_TAKEN',
  USERNAME_INVALID = 'USERNAME_INVALID',
  WISHMATE_SELF = 'WISHMATE_SELF',
  WISHLINK_NOT_FOUND = 'WISHLINK_NOT_FOUND',
  WISHLINK_ALREADY_EXISTS = 'WISHLINK_ALREADY_EXISTS',
  NOT_WISHMATES = 'NOT_WISHMATES',

  WEBHOOK_SIGNATURE_INVALID = 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_TIMESTAMP_INVALID = 'WEBHOOK_TIMESTAMP_INVALID',
  WEBHOOK_PROVIDER_UNKNOWN = 'WEBHOOK_PROVIDER_UNKNOWN',

  // Group gifting
  GROUP_GIFT_NOT_FOUND = 'GROUP_GIFT_NOT_FOUND',
  GROUP_GIFT_NOT_OPEN = 'GROUP_GIFT_NOT_OPEN',
  GROUP_GIFT_CLOSED = 'GROUP_GIFT_CLOSED',
  /**
   * The bill — gifts and charges — is frozen because someone has already
   * contributed. Distinct from GROUP_GIFT_NOT_OPEN so the client can offer the
   * one thing that still works (a contribution request) rather than telling
   * the host their group is closed, which it is not.
   */
  GROUP_GIFT_BILL_LOCKED = 'GROUP_GIFT_BILL_LOCKED',
  CONTRIBUTION_EXCEEDS_TARGET = 'CONTRIBUTION_EXCEEDS_TARGET',
  CONTRIBUTION_NOT_FOUND = 'CONTRIBUTION_NOT_FOUND',
  CONTRIBUTION_AMOUNT_INVALID = 'CONTRIBUTION_AMOUNT_INVALID',
  NOT_THE_CONTRIBUTOR = 'NOT_THE_CONTRIBUTOR',
  NOT_THE_INITIATOR = 'NOT_THE_INITIATOR',
  INVALID_GROUP_GIFT_TRANSITION = 'INVALID_GROUP_GIFT_TRANSITION',
  GROUP_GIFT_DEADLINE_INVALID = 'GROUP_GIFT_DEADLINE_INVALID',

  // Chat
  CHAT_NOT_FOUND = 'CHAT_NOT_FOUND',
  CHAT_DISABLED = 'CHAT_DISABLED',
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
  NOT_THE_SENDER = 'NOT_THE_SENDER',
  MESSAGE_EMPTY = 'MESSAGE_EMPTY',
  MESSAGE_TOO_LONG = 'MESSAGE_TOO_LONG',
  CANNOT_POST_IN_CHAT = 'CANNOT_POST_IN_CHAT',
  WS_UNAUTHENTICATED = 'WS_UNAUTHENTICATED',
  CHAT_RATE_LIMITED = 'CHAT_RATE_LIMITED',

  // Notifications
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  UNSUBSCRIBE_TOKEN_INVALID = 'UNSUBSCRIBE_TOKEN_INVALID',
  THANK_YOU_NOTE_NOT_FOUND = 'THANK_YOU_NOTE_NOT_FOUND',
  THANK_YOU_ALREADY_SENT = 'THANK_YOU_ALREADY_SENT',
  THANK_YOU_MEDIA_REQUIRED = 'THANK_YOU_MEDIA_REQUIRED',

  // ── Addresses (Sprint 9) ──────────────────────────────────────────────────
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
  ADDRESS_LIMIT_REACHED = 'ADDRESS_LIMIT_REACHED',
  NOT_THE_SENDER_OF_NOTE = 'NOT_THE_SENDER_OF_NOTE',
  BOUNCE_SIGNATURE_INVALID = 'BOUNCE_SIGNATURE_INVALID',

  // Reels
  REEL_COLLECTION_NOT_FOUND = 'REEL_COLLECTION_NOT_FOUND',
  REEL_NOT_ACCEPTING_WISHES = 'REEL_NOT_ACCEPTING_WISHES',
  REEL_NOT_RELEASED = 'REEL_NOT_RELEASED',
  WISH_NOT_FOUND = 'WISH_NOT_FOUND',
  WISH_MEDIA_REQUIRED = 'WISH_MEDIA_REQUIRED',
  WISH_MEDIA_INVALID = 'WISH_MEDIA_INVALID',
  WISH_DURATION_EXCEEDED = 'WISH_DURATION_EXCEEDED',
  WISH_TEXT_REQUIRED = 'WISH_TEXT_REQUIRED',
  INVALID_REEL_TRANSITION = 'INVALID_REEL_TRANSITION',
  CANNOT_RECEIVE_OWN_REEL = 'CANNOT_RECEIVE_OWN_REEL',

  // Memories
  MEMORY_NOT_FOUND = 'MEMORY_NOT_FOUND',
  MEMORY_NOT_ACCEPTING_WISHES = 'MEMORY_NOT_ACCEPTING_WISHES',
  MEMORY_LOCKED = 'MEMORY_LOCKED',
  MEMORY_WISH_NOT_FOUND = 'MEMORY_WISH_NOT_FOUND',
  MEMORY_WISH_MEDIA_REQUIRED = 'MEMORY_WISH_MEDIA_REQUIRED',
  MEMORY_WISH_TEXT_REQUIRED = 'MEMORY_WISH_TEXT_REQUIRED',
  INVALID_MEMORY_TRANSITION = 'INVALID_MEMORY_TRANSITION',
  /** Nobody on the list actually sent the caller a memory. */
  MEMORY_REPLY_NO_AUDIENCE = 'MEMORY_REPLY_NO_AUDIENCE',
  MEMORY_REPLY_NOT_FOUND = 'MEMORY_REPLY_NOT_FOUND',

  // Admin / moderation / analytics
  ADMIN_UNAUTHENTICATED = 'ADMIN_UNAUTHENTICATED',
  ADMIN_FORBIDDEN = 'ADMIN_FORBIDDEN',
  ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND',
  ADMIN_CREDENTIALS_INVALID = 'ADMIN_CREDENTIALS_INVALID',
  ADMIN_TOTP_REQUIRED = 'ADMIN_TOTP_REQUIRED',
  ADMIN_TOTP_INVALID = 'ADMIN_TOTP_INVALID',
  ADMIN_TOTP_ALREADY_ENABLED = 'ADMIN_TOTP_ALREADY_ENABLED',
  ADMIN_IP_NOT_ALLOWED = 'ADMIN_IP_NOT_ALLOWED',
  ADMIN_DISABLED = 'ADMIN_DISABLED',
  REPORT_NOT_FOUND = 'REPORT_NOT_FOUND',
  REPORT_ALREADY_HANDLED = 'REPORT_ALREADY_HANDLED',
  INVALID_MODERATION_TARGET = 'INVALID_MODERATION_TARGET',

  // Events & invites
  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
  EVENT_NOT_PUBLISHED = 'EVENT_NOT_PUBLISHED',
  EVENT_ALREADY_PUBLISHED = 'EVENT_ALREADY_PUBLISHED',
  EVENT_CANCELLED = 'EVENT_CANCELLED',
  EVENT_DATE_IN_PAST = 'EVENT_DATE_IN_PAST',
  EVENT_LIMIT_REACHED = 'EVENT_LIMIT_REACHED',
  INVITE_NOT_FOUND = 'INVITE_NOT_FOUND',
  INVITE_TOKEN_INVALID = 'INVITE_TOKEN_INVALID',
  INVITE_LIMIT_REACHED = 'INVITE_LIMIT_REACHED',
  INVITE_TEMPLATE_UNKNOWN = 'INVITE_TEMPLATE_UNKNOWN',
  CANNOT_INVITE_HOST = 'CANNOT_INVITE_HOST',
  /**
   * The link is for a private event and the caller is not on its guest list.
   *
   * Distinct from EVENT_NOT_FOUND on purpose. A private event's link used to
   * 404 so a stranger could not learn it existed, but a host now sends that
   * link to phone numbers, and the people who receive it need to be told why
   * it will not open rather than shown a dead page. The slug is still
   * unguessable, so what leaks is only "the link you were sent is real".
   */
  EVENT_INVITE_REQUIRED = 'EVENT_INVITE_REQUIRED',
  WISHLIST_NOT_LINKABLE = 'WISHLIST_NOT_LINKABLE',

  // Products / affiliate
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_PROVIDER_UNKNOWN = 'PRODUCT_PROVIDER_UNKNOWN',
  /** The upstream catalogue is down and we have nothing cached to fall back on. */
  PRODUCT_SEARCH_UNAVAILABLE = 'PRODUCT_SEARCH_UNAVAILABLE',
  PRODUCT_URL_UNSUPPORTED = 'PRODUCT_URL_UNSUPPORTED',
  PRODUCT_URL_UNREACHABLE = 'PRODUCT_URL_UNREACHABLE',
  /** The URL resolves to an address the server must never fetch. See SsrfGuard. */
  URL_NOT_ALLOWED = 'URL_NOT_ALLOWED',

  // Media
  MEDIA_TYPE_NOT_ALLOWED = 'MEDIA_TYPE_NOT_ALLOWED',
  MEDIA_TOO_LARGE = 'MEDIA_TOO_LARGE',
  MEDIA_TOO_LONG = 'MEDIA_TOO_LONG',
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  MEDIA_NOT_UPLOADED = 'MEDIA_NOT_UPLOADED',
  MEDIA_SIGNATURE_INVALID = 'MEDIA_SIGNATURE_INVALID',
  MEDIA_URL_EXPIRED = 'MEDIA_URL_EXPIRED',

  // OTP / reset
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS = 'OTP_MAX_ATTEMPTS',
  OTP_COOLDOWN = 'OTP_COOLDOWN',
  RESET_TOKEN_INVALID = 'RESET_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED = 'RESET_TOKEN_EXPIRED',
}
